FROM alpine:latest
MAINTAINER Talmai Oliveira <to@talm.ai>

RUN     apk update && \
        apk upgrade && \
        apk add --update nginx && \
        mkdir -p /var/run/nginx && \
        mkdir -p /usr/share/nginx/html && \
        mkdir /var/tmp/nginx && \
        chown nobody /var/tmp/nginx && \
        rm -rf /var/cache/apk/*

COPY docker_nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker_nginx/common.conf /etc/nginx/common.conf
COPY docker_nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# Expose volumes
VOLUME ["/etc/nginx/conf.d", "/var/log/nginx"]

# Expose ports
EXPOSE 80

# Entry point
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
